"""empty message

Revision ID: 136bf4411930
Revises: 6f3aaa433f07
Create Date: 2025-04-18 23:41:28.224792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136bf4411930'
down_revision = '6f3aaa433f07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ru_brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('celebrity_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('celebrity_img', sa.String(length=200), nullable=False))
        batch_op.drop_column('brand_name')
        batch_op.drop_column('brand_img')

    with op.batch_alter_table('ru_outfits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('celebrity_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'ru_brands', ['celebrity_id'], ['id'])
        batch_op.drop_column('brand_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ru_outfits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'ru_brands', ['brand_id'], ['id'])
        batch_op.drop_column('celebrity_id')

    with op.batch_alter_table('ru_brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_img', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('brand_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('celebrity_img')
        batch_op.drop_column('celebrity_name')

    # ### end Alembic commands ###
