"""empty message

Revision ID: 4cfe486fc68b
Revises: 
Create Date: 2025-04-10 16:30:11.507231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cfe486fc68b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cis_celebrities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_id', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint('cis_celebrities', ['unique_id'])

    with op.batch_alter_table('ru_brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_id', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint('ru_brands', ['unique_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ru_brands', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('unique_id')

    with op.batch_alter_table('cis_celebrities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('unique_id')

    # ### end Alembic commands ###
