"""empty message

Revision ID: 81d0c224afe3
Revises: ba5e2f01fc80
Create Date: 2025-04-18 16:56:04.430384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d0c224afe3'
down_revision = 'ba5e2f01fc80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_foreign_outfits')
    with op.batch_alter_table('cis_outfits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(length=200), nullable=False))

    with op.batch_alter_table('foreign_outfits', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foreign_outfits', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=300),
               nullable=True)

    with op.batch_alter_table('cis_outfits', schema=None) as batch_op:
        batch_op.drop_column('link')

    op.create_table('_alembic_tmp_foreign_outfits',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('outfit_item', sa.VARCHAR(length=100), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('item_img', sa.VARCHAR(length=200), nullable=False),
    sa.Column('celebrity_id', sa.INTEGER(), nullable=False),
    sa.Column('link', sa.VARCHAR(length=200), nullable=False),
    sa.ForeignKeyConstraint(['celebrity_id'], ['foreign_celebrities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
