"""empty message

Revision ID: b8d74c6c3c36
Revises: 81d0c224afe3
Create Date: 2025-04-18 17:00:56.146676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8d74c6c3c36'
down_revision = '81d0c224afe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cis_outfits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(length=200), nullable=True))

    with op.batch_alter_table('foreign_outfits', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foreign_outfits', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=300),
               nullable=True)

    with op.batch_alter_table('cis_outfits', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###
