"""empty message

Revision ID: ba5e2f01fc80
Revises: 2f44d31ae49a
Create Date: 2025-04-17 21:25:00.267872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5e2f01fc80'
down_revision = '2f44d31ae49a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foreign_outfits', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foreign_outfits', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=300),
               nullable=True)

    # ### end Alembic commands ###
